<?php

namespace AppBundle\Repository;

/**
 * CharteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharteRepository extends \Doctrine\ORM\EntityRepository
{
}
