<?php

namespace AppBundle\Repository;

/**
 * Check_liste_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Check_liste_userRepository extends \Doctrine\ORM\EntityRepository
{
}
