<?php

namespace AppBundle\Repository;

/**
 * Demande_expoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_expoRepository extends \Doctrine\ORM\EntityRepository
{
}
