<?php

namespace AppBundle\Repository;

/**
 * ExpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionRepository extends \Doctrine\ORM\EntityRepository
{
}
