<?php

namespace AppBundle\Repository;

/**
 * ImagesPlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesPlacesRepository extends \Doctrine\ORM\EntityRepository
{
}
