<?php

namespace AppBundle\Repository;

/**
 * Note_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Note_userRepository extends \Doctrine\ORM\EntityRepository
{
}
