<?php

namespace AppBundle\Repository;

/**
 * Place_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Place_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
