<?php

namespace AppBundle\Repository;

/**
 * Serie_pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Serie_pictureRepository extends \Doctrine\ORM\EntityRepository
{
}
