<?php

namespace AppBundle\Repository;

/**
 * serieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serieRepository extends \Doctrine\ORM\EntityRepository
{
}
