<?php

namespace AppBundle\Repository;

/**
 * Style_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Style_userRepository extends \Doctrine\ORM\EntityRepository
{
}
