<?php

namespace AppBundle\Repository;

/**
 * Style_pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Style_pictureRepository extends \Doctrine\ORM\EntityRepository
{
}
