<?php

namespace AppBundle\Repository;

/**
 * SuggestionCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionCatRepository extends \Doctrine\ORM\EntityRepository
{
}
