<?php

namespace AppBundle\Repository;

/**
 * TechniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechniqueRepository extends \Doctrine\ORM\EntityRepository
{
}
