security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
         in_memory:
            memory: 
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern : ^/
            anonymous: true
            provider: in_memory
            form_login:
                check_path: loginCheck
                login_path: login
                default_target_path: /login
            logout:
                path: logout
                target: /login
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: plaintext
            ignore_case: false       
            
    access_control:   
     
        - { path: ^/admin, roles: [ROLE_ADMIN , ROLE_USER] } 
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html