AppBundle\Entity\Charte:
    type: entity
    table: charte
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        picture:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        contenu:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
