AppBundle\Entity\CheckListeModel:
    type: entity
    table: check_liste_model
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        task:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        checkend:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
