AppBundle\Entity\Message:
    type: entity
    table: message
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        message:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        hour:
            type: datetime
            nullable: false
        exposition:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
