AppBundle\Entity\NoteUser:
    type: entity
    table: note_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Note
        field:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
