AppBundle\Entity\Serie:
    type: entity
    table: serie
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: integer
            nullable: false
            options:
                unsigned: false
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
