AppBundle\Entity\SeriePicture:
    type: entity
    table: serie_picture
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        serie:
            type: integer
            nullable: false
            options:
                unsigned: false
        pictures:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
