AppBundle\Entity\StyleUser:
    type: entity
    table: style_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        style:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
