AppBundle\Entity\Wishlist:
    type: entity
    table: wishlist
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        artiste:
            type: integer
            nullable: false
            options:
                unsigned: false
        usermain:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
